on:
  push:
    tags:
    - '*'
    - '!*.x'

jobs:
  release-create:
    name: Create BW-Linux-Scripts Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get Current Release Version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: Release v${{ steps.get_version.outputs.VERSION }}
        body: |
          BW-Linux-Scripts Release v${{ steps.get_version.outputs.VERSION }}
          
          For full change details read the [CHANGELOG](/CHANGELOG.md)
  assets-matrix:
    name: Create Release Assets
    runs-on: ubuntu-latest
    needs: release-create
    strategy:
      matrix:
        scripts: [bw-snapshot]
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
    steps:
    - uses: actions/checkout@v2
    - name: Get Current Release Version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
    - uses: wangyoucao577/go-release-action@v1.26
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        asset_name: ${{ matrix.scripts }}-${{ steps.get_version.outputs.VERSION }}-${{ matrix.goos }}-${{ matrix.goarch }}
        build_command: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o ${{ matrix.scripts }} ./cmd/${{ matrix.scripts }}
        binary_name: ${{ matrix.scripts }}
        extra_files: CHANGELOG.md